//
// GENERATED FILE - do not edit by hand.
// Rebuild with: python tools/generate-catalogue.py
//
// Every armed, non-VTOL design the game ships, with the metadata the wave
// generator selects on:
//
//   d  design, in the form Template.fromString() reads
//   c  power cost
//   k  class    scavenger, cyborg, cyborg_super, tank_light, tank_medium, tank_heavy
//   f  family   mg, cannon, rocket, missile, flame, energy, gauss, mortar, howitzer
//   t  tier     0 cheapest .. 5 dearest, from cost brackets
//   s  size     light, medium or heavy - the weight thirds of its own
//                tier, so every tier holds all three
//   w  weight   body + propulsion + guns, as the game computes it
//   b  body     chassis name, for boss curves written as a chassis list
//   i  indirect fire (artillery), absent when direct
//

// The highest tier present, so the wave generator knows where the top is
const TOP_TIER = 5;

const CATALOGUE = [
	{ d: "*BusCannon* *School Bus Body* BaBaProp", c: 14, w: 2210, k: "scavenger", s: "heavy", f: "cannon", t: 0, b: "*School Bus Body*" },
	{ d: "*BusCannon* *Fire Engine Body* BaBaProp", c: 14, w: 3310, k: "scavenger", s: "heavy", f: "cannon", t: 0, b: "*Fire Engine Body*" },
	{ d: "*Flamer* *Fire Engine Body* BaBaProp", c: 44, w: 3310, k: "scavenger", s: "heavy", f: "flame", t: 0, b: "*Fire Engine Body*" },
	{ d: "*BaBa MG* *BaBa Body* BaBaLegs", c: 2, w: 111, k: "scavenger", s: "light", f: "mg", t: 0, b: "*BaBa Body*" },
	{ d: "*Trike MG* *Trike Body* BaBaProp", c: 4, w: 743, k: "scavenger", s: "light", f: "mg", t: 0, b: "*Trike Body*" },
	{ d: "*Buggy MG* *Buggy Body* BaBaProp", c: 6, w: 991, k: "scavenger", s: "medium", f: "mg", t: 0, b: "*Buggy Body*" },
	{ d: "*Jeep MG* *Jeep Body* BaBaProp", c: 8, w: 991, k: "scavenger", s: "medium", f: "mg", t: 0, b: "*Jeep Body*" },
	{ d: "*BabaRocket* *Rocket Buggy Body* BaBaProp", c: 13, w: 1090, k: "scavenger", s: "medium", f: "rocket", t: 0, b: "*Rocket Buggy Body*" },
	{ d: "*BabaRocket* *Rocket Jeep Body* BaBaProp", c: 14, w: 1090, k: "scavenger", s: "medium", f: "rocket", t: 0, b: "*Rocket Jeep Body*" },
	{ d: "*Kevs Super Weapon* *Kev's Super Body* Hover", c: 35, w: 8200, k: "tank_heavy", s: "heavy", f: "mg", t: 1, b: "*Kev's Super Body*" },
	{ d: "*Alexs Super Weapon* *Kev's Super Body* Hover", c: 35, w: 8200, k: "tank_heavy", s: "heavy", f: "cannon", t: 1, b: "*Kev's Super Body*" },
	{ d: "Machinegun Scorpion Half-tracks", c: 78, w: 7700, k: "tank_medium", s: "heavy", f: "mg", t: 1, b: "Scorpion" },
	{ d: "Twin Machinegun Viper Tracks", c: 92, w: 4900, k: "tank_light", s: "heavy", f: "mg", t: 1, b: "Viper" },
	{ d: "Machinegun Viper Wheels", c: 55, w: 2600, k: "tank_light", s: "light", f: "mg", t: 1, b: "Viper" },
	{ d: "Machinegunner Cyborg Light Body Cyborg Propulsion", c: 67, w: 345, k: "cyborg", s: "light", f: "mg", t: 1, b: "Cyborg Light Body" },
	{ d: "Cyborg Flamer Cyborg Light Body Cyborg Propulsion", c: 82, w: 345, k: "cyborg", s: "light", f: "flame", t: 1, b: "Cyborg Light Body" },
	{ d: "Heavy Gunner Cyborg Light Body Cyborg Propulsion", c: 87, w: 345, k: "cyborg", s: "light", f: "cannon", t: 1, b: "Cyborg Light Body" },
	{ d: "Machinegun Viper Half-tracks", c: 62, w: 3200, k: "tank_light", s: "medium", f: "mg", t: 1, b: "Viper" },
	{ d: "Twin Machinegun Viper Wheels", c: 70, w: 2800, k: "tank_light", s: "medium", f: "mg", t: 1, b: "Viper" },
	{ d: "Twin Machinegun Viper Half-tracks", c: 77, w: 3400, k: "tank_light", s: "medium", f: "mg", t: 1, b: "Viper" },
	{ d: "Machinegun Viper Tracks", c: 77, w: 4700, k: "tank_light", s: "medium", f: "mg", t: 1, b: "Viper" },
	{ d: "Heavy Machinegun Bug Half-tracks", c: 93, w: 2850, k: "tank_light", s: "medium", f: "mg", t: 1, b: "Bug" },
	{ d: "Heavy Machinegun Viper Wheels", c: 95, w: 3000, k: "tank_light", s: "medium", f: "mg", t: 1, b: "Viper" },
	{ d: "Heavy Machinegun Cobra Wheels", c: 119, w: 8600, k: "tank_medium", s: "heavy", f: "mg", t: 2, b: "Cobra" },
	{ d: "Heavy Machinegun Cobra Half-tracks", c: 130, w: 10600, k: "tank_medium", s: "heavy", f: "mg", t: 2, b: "Cobra" },
	{ d: "Heavy Machinegun Scorpion Tracks", c: 137, w: 11850, k: "tank_medium", s: "heavy", f: "mg", t: 2, b: "Scorpion" },
	{ d: "Light Cannon Scorpion Half-tracks", c: 143, w: 8500, k: "tank_medium", s: "heavy", f: "cannon", t: 2, b: "Scorpion" },
	{ d: "Mini-Rocket Pod Cobra Half-tracks", c: 150, w: 10200, k: "tank_medium", s: "heavy", f: "rocket", t: 2, b: "Cobra" },
	{ d: "Heavy Machinegun Cobra Tracks", c: 153, w: 15600, k: "tank_medium", s: "heavy", f: "mg", t: 2, b: "Cobra" },
	{ d: "Flamer Cobra Tracks", c: 163, w: 15250, k: "tank_medium", s: "heavy", f: "flame", t: 2, b: "Cobra" },
	{ d: "Heavy Machinegun Cobra Hover", c: 165, w: 6600, k: "tank_medium", s: "heavy", f: "mg", t: 2, b: "Cobra" },
	{ d: "Mortar Scorpion Half-tracks", c: 173, w: 9500, k: "tank_medium", s: "heavy", f: "mortar", t: 2, b: "Scorpion", i: 1 },
	{ d: "Mini-Rocket Pod Cobra Tracks", c: 173, w: 15200, k: "tank_medium", s: "heavy", f: "rocket", t: 2, b: "Cobra" },
	{ d: "Heavy Machinegun Panther Tracks", c: 178, w: 19350, k: "tank_medium", s: "heavy", f: "mg", t: 2, b: "Panther" },
	{ d: "Light Cannon Cobra Tracks", c: 178, w: 16000, k: "tank_medium", s: "heavy", f: "cannon", t: 2, b: "Cobra" },
	{ d: "Mini-Rocket Array Cobra Half-tracks", c: 180, w: 10250, k: "tank_medium", s: "heavy", f: "rocket", t: 2, b: "Cobra", i: 1 },
	{ d: "Mortar Cobra Half-tracks", c: 185, w: 12000, k: "tank_medium", s: "heavy", f: "mortar", t: 2, b: "Cobra", i: 1 },
	{ d: "Inferno Cobra Half-tracks", c: 190, w: 15000, k: "tank_medium", s: "heavy", f: "flame", t: 2, b: "Cobra" },
	{ d: "Cyborg Thermite Cyborg Light Body Cyborg Propulsion", c: 102, w: 345, k: "cyborg", s: "light", f: "flame", t: 2, b: "Cyborg Light Body" },
	{ d: "Mini-Rocket Pod Bug Wheels", c: 107, w: 2000, k: "tank_light", s: "light", f: "rocket", t: 2, b: "Bug" },
	{ d: "*Cyborg Grenade Weapon* Cyborg Light Body Cyborg Propulsion", c: 107, w: 345, k: "cyborg", s: "light", f: "mortar", t: 2, b: "Cyborg Light Body", i: 1 },
	{ d: "Heavy Machinegun Bug Hover", c: 112, w: 1950, k: "tank_light", s: "light", f: "mg", t: 2, b: "Bug" },
	{ d: "*CyborgRotMG* Cyborg Light Body Cyborg Propulsion", c: 117, w: 345, k: "cyborg", s: "light", f: "mg", t: 2, b: "Cyborg Light Body" },
	{ d: "*Cyb-Wpn-Laser* Cyborg Light Body Cyborg Propulsion", c: 127, w: 345, k: "cyborg", s: "light", f: "energy", t: 2, b: "Cyborg Light Body" },
	{ d: "*Cyborg Thermite Weapon* Cyborg Light Body Cyborg Propulsion", c: 127, w: 345, k: "cyborg", s: "light", f: "flame", t: 2, b: "Cyborg Light Body" },
	{ d: "Super Heavy-Gunner Cyborg Heavy Body Cyborg Propulsion", c: 130, w: 495, k: "cyborg_super", s: "light", f: "cannon", t: 2, b: "Cyborg Heavy Body" },
	{ d: "Cyborg Lancer Cyborg Light Body Cyborg Propulsion", c: 152, w: 345, k: "cyborg", s: "light", f: "rocket", t: 2, b: "Cyborg Light Body" },
	{ d: "Sniper Cyborg Cyborg Light Body Cyborg Propulsion", c: 157, w: 345, k: "cyborg", s: "light", f: "cannon", t: 2, b: "Cyborg Light Body" },
	{ d: "*NX-CyborgPulseLas* *CybNXPulseLasJ* Cyborg Propulsion", c: 158, w: 345, k: "cyborg", s: "light", f: "energy", t: 2, b: "*CybNXPulseLasJ*" },
	{ d: "Super Auto-Cannon Cyborg Cyborg Heavy Body Cyborg Propulsion", c: 180, w: 495, k: "cyborg_super", s: "light", f: "cannon", t: 2, b: "Cyborg Heavy Body" },
	{ d: "*Cyb-Wpn-Rail1* Cyborg Light Body Cyborg Propulsion", c: 187, w: 345, k: "cyborg", s: "light", f: "gauss", t: 2, b: "Cyborg Light Body" },
	{ d: "Cyborg Tank Killer Cyborg Light Body Cyborg Propulsion", c: 187, w: 345, k: "cyborg", s: "light", f: "rocket", t: 2, b: "Cyborg Light Body" },
	{ d: "Heavy Machinegun Viper Half-tracks", c: 102, w: 3600, k: "tank_light", s: "medium", f: "mg", t: 2, b: "Viper" },
	{ d: "Flamer Viper Wheels", c: 105, w: 2650, k: "tank_light", s: "medium", f: "flame", t: 2, b: "Viper" },
	{ d: "Flamer Viper Half-tracks", c: 112, w: 3250, k: "tank_light", s: "medium", f: "flame", t: 2, b: "Viper" },
	{ d: "Mini-Rocket Pod Viper Wheels", c: 115, w: 2600, k: "tank_light", s: "medium", f: "rocket", t: 2, b: "Viper" },
	{ d: "Heavy Machinegun Viper Tracks", c: 117, w: 5100, k: "tank_light", s: "medium", f: "mg", t: 2, b: "Viper" },
	{ d: "Light Cannon Bug Half-tracks", c: 118, w: 3250, k: "tank_light", s: "medium", f: "cannon", t: 2, b: "Bug" },
	{ d: "Light Cannon Viper Wheels", c: 120, w: 3400, k: "tank_light", s: "medium", f: "cannon", t: 2, b: "Viper" },
	{ d: "Mini-Rocket Pod Viper Half-tracks", c: 122, w: 3200, k: "tank_light", s: "medium", f: "rocket", t: 2, b: "Viper" },
	{ d: "Light Cannon Viper Half-tracks", c: 127, w: 4000, k: "tank_light", s: "medium", f: "cannon", t: 2, b: "Viper" },
	{ d: "Light Cannon Viper Tracks", c: 142, w: 5500, k: "tank_light", s: "medium", f: "cannon", t: 2, b: "Viper" },
	{ d: "Mini-Rocket Array Bug Half-tracks", c: 143, w: 2500, k: "tank_light", s: "medium", f: "rocket", t: 2, b: "Bug", i: 1 },
	{ d: "Mini-Rocket Array Viper Wheels", c: 145, w: 2650, k: "tank_light", s: "medium", f: "rocket", t: 2, b: "Viper", i: 1 },
	{ d: "Heavy Machinegun Scorpion Hover", c: 147, w: 5100, k: "tank_medium", s: "medium", f: "mg", t: 2, b: "Scorpion" },
	{ d: "Mini-Rocket Array Viper Half-tracks", c: 152, w: 3250, k: "tank_light", s: "medium", f: "rocket", t: 2, b: "Viper", i: 1 },
	{ d: "Assault Gun Leopard Half-tracks", c: 189, w: 4350, k: "tank_light", s: "medium", f: "mg", t: 2, b: "Leopard" },
	{ d: "Lancer Bug Half-tracks", c: 193, w: 2500, k: "tank_light", s: "medium", f: "rocket", t: 2, b: "Bug" },
	{ d: "Bunker Buster Viper Wheels", c: 195, w: 2650, k: "tank_light", s: "medium", f: "rocket", t: 2, b: "Viper" },
	{ d: "Lancer Viper Wheels", c: 195, w: 2650, k: "tank_light", s: "medium", f: "rocket", t: 2, b: "Viper" },
	{ d: "Light Cannon Python Tracks", c: 210, w: 21250, k: "tank_heavy", s: "heavy", f: "cannon", t: 3, b: "Python" },
	{ d: "Medium Cannon Scorpion Tracks", c: 237, w: 16250, k: "tank_medium", s: "heavy", f: "cannon", t: 3, b: "Scorpion" },
	{ d: "Inferno Panther Tracks", c: 238, w: 23750, k: "tank_medium", s: "heavy", f: "flame", t: 3, b: "Panther" },
	{ d: "Assault Gun Panther Tracks", c: 253, w: 19350, k: "tank_medium", s: "heavy", f: "mg", t: 3, b: "Panther" },
	{ d: "Medium Cannon Cobra Tracks", c: 253, w: 20000, k: "tank_medium", s: "heavy", f: "cannon", t: 3, b: "Cobra" },
	{ d: "AA Cyclone Flak Cannon Python Half-tracks", c: 255, w: 17500, k: "tank_heavy", s: "heavy", f: "cannon", t: 3, b: "Python" },
	{ d: "Assault Gun Python Tracks", c: 260, w: 20850, k: "tank_heavy", s: "heavy", f: "mg", t: 3, b: "Python" },
	{ d: "Medium Cannon Mantis Tracks", c: 267, w: 20750, k: "tank_heavy", s: "heavy", f: "cannon", t: 3, b: "Mantis" },
	{ d: "AA Cyclone Flak Cannon Panther Tracks", c: 278, w: 22750, k: "tank_medium", s: "heavy", f: "cannon", t: 3, b: "Panther" },
	{ d: "Medium Cannon Panther Tracks", c: 278, w: 23750, k: "tank_medium", s: "heavy", f: "cannon", t: 3, b: "Panther" },
	{ d: "Lancer Panther Tracks", c: 278, w: 19000, k: "tank_medium", s: "heavy", f: "rocket", t: 3, b: "Panther" },
	{ d: "Hyper Velocity Cannon Cobra Tracks", c: 278, w: 18000, k: "tank_medium", s: "heavy", f: "cannon", t: 3, b: "Cobra" },
	{ d: "Medium Cannon Python Tracks", c: 285, w: 25250, k: "tank_heavy", s: "heavy", f: "cannon", t: 3, b: "Python" },
	{ d: "Lancer Python Tracks", c: 285, w: 20500, k: "tank_heavy", s: "heavy", f: "rocket", t: 3, b: "Python" },
	{ d: "Hyper Velocity Cannon Panther Tracks", c: 303, w: 21750, k: "tank_medium", s: "heavy", f: "cannon", t: 3, b: "Panther" },
	{ d: "Pepperpot Panther Tracks", c: 303, w: 20750, k: "tank_medium", s: "heavy", f: "mortar", t: 3, b: "Panther", i: 1 },
	{ d: "Bunker Buster Tiger Tracks", c: 309, w: 25000, k: "tank_heavy", s: "heavy", f: "rocket", t: 3, b: "Tiger" },
	{ d: "Assault Cannon Tiger Tracks", c: 309, w: 27250, k: "tank_heavy", s: "heavy", f: "cannon", t: 3, b: "Tiger" },
	{ d: "Hyper Velocity Cannon Python Tracks", c: 310, w: 23250, k: "tank_heavy", s: "heavy", f: "cannon", t: 3, b: "Python" },
	{ d: "Pulse Laser Mantis Tracks", c: 317, w: 16250, k: "tank_heavy", s: "heavy", f: "energy", t: 3, b: "Mantis" },
	{ d: "Tank Killer Mantis Tracks", c: 317, w: 16050, k: "tank_heavy", s: "heavy", f: "rocket", t: 3, b: "Mantis" },
	{ d: "Bombard Panther Tracks", c: 328, w: 23750, k: "tank_medium", s: "heavy", f: "mortar", t: 3, b: "Panther", i: 1 },
	{ d: "Tank Killer Panther Tracks", c: 328, w: 19050, k: "tank_medium", s: "heavy", f: "rocket", t: 3, b: "Panther" },
	{ d: "Hyper Velocity Cannon Tiger Tracks", c: 334, w: 27750, k: "tank_heavy", s: "heavy", f: "cannon", t: 3, b: "Tiger" },
	{ d: "Tank Killer Python Tracks", c: 335, w: 20550, k: "tank_heavy", s: "heavy", f: "rocket", t: 3, b: "Python" },
	{ d: "Pulse Laser Python Tracks", c: 335, w: 20750, k: "tank_heavy", s: "heavy", f: "energy", t: 3, b: "Python" },
	{ d: "Heavy Cannon Scorpion Tracks", c: 337, w: 19250, k: "tank_medium", s: "heavy", f: "cannon", t: 3, b: "Scorpion" },
	{ d: "Flashlight Wyvern Tracks", c: 343, w: 26550, k: "tank_heavy", s: "heavy", f: "energy", t: 3, b: "Wyvern" },
	{ d: "Super HVC Cyborg Cyborg Heavy Body Cyborg Propulsion", c: 205, w: 495, k: "cyborg_super", s: "light", f: "cannon", t: 3, b: "Cyborg Heavy Body" },
	{ d: "Super Pulse Laser Cyborg Cyborg Heavy Body Cyborg Propulsion", c: 205, w: 495, k: "cyborg_super", s: "light", f: "energy", t: 3, b: "Cyborg Heavy Body" },
	{ d: "Lancer Viper Tracks", c: 217, w: 4750, k: "tank_light", s: "light", f: "rocket", t: 3, b: "Viper" },
	{ d: "Bunker Buster Scorpion Half-tracks", c: 218, w: 7750, k: "tank_medium", s: "light", f: "rocket", t: 3, b: "Scorpion" },
	{ d: "Assault Gun Scorpion Hover", c: 222, w: 5100, k: "tank_medium", s: "light", f: "mg", t: 3, b: "Scorpion" },
	{ d: "*NX-Cyb-Rail1* *CybNXRail1Jmp* Cyborg Propulsion", c: 233, w: 345, k: "cyborg", s: "light", f: "gauss", t: 3, b: "*CybNXRail1Jmp*" },
	{ d: "Lancer Leopard Tracks", c: 233, w: 5875, k: "tank_light", s: "light", f: "rocket", t: 3, b: "Leopard" },
	{ d: "Lancer Scorpion Hover", c: 247, w: 4750, k: "tank_medium", s: "light", f: "rocket", t: 3, b: "Scorpion" },
	{ d: "Bunker Buster Scorpion Hover", c: 247, w: 4750, k: "tank_medium", s: "light", f: "rocket", t: 3, b: "Scorpion" },
	{ d: "Super Tank-Killer Cyborg Cyborg Heavy Body Cyborg Propulsion", c: 255, w: 495, k: "cyborg_super", s: "light", f: "rocket", t: 3, b: "Cyborg Heavy Body" },
	{ d: "*Cyb-Wpn-Atmiss* Cyborg Light Body Cyborg Propulsion", c: 260, w: 345, k: "cyborg", s: "light", f: "missile", t: 3, b: "Cyborg Light Body" },
	{ d: "Flashlight Retaliation Hover", c: 262, w: 1650, k: "tank_light", s: "light", f: "energy", t: 3, b: "Retaliation" },
	{ d: "Bunker Buster Cobra Hover", c: 265, w: 6250, k: "tank_medium", s: "light", f: "rocket", t: 3, b: "Cobra" },
	{ d: "Lancer Cobra Hover", c: 265, w: 6250, k: "tank_medium", s: "light", f: "rocket", t: 3, b: "Cobra" },
	{ d: "Assault Gun Python Hover", c: 275, w: 8700, k: "tank_heavy", s: "light", f: "mg", t: 3, b: "Python" },
	{ d: "Assault Cannon Mantis Hover", c: 280, w: 8800, k: "tank_heavy", s: "light", f: "cannon", t: 3, b: "Mantis" },
	{ d: "*NX-CyborgMiss* *CybNXMissJmp* Cyborg Propulsion", c: 283, w: 345, k: "cyborg", s: "light", f: "missile", t: 3, b: "*CybNXMissJmp*" },
	{ d: "Super Scourge Cyborg Cyborg Heavy Body Cyborg Propulsion", c: 290, w: 495, k: "cyborg_super", s: "light", f: "missile", t: 3, b: "Cyborg Heavy Body" },
	{ d: "Lancer Panther Hover", c: 292, w: 7750, k: "tank_medium", s: "light", f: "rocket", t: 3, b: "Panther" },
	{ d: "Pulse Laser Leopard Hover", c: 292, w: 2750, k: "tank_light", s: "light", f: "energy", t: 3, b: "Leopard" },
	{ d: "Super Rail-Gunner Cyborg Heavy Body Cyborg Propulsion", c: 295, w: 495, k: "cyborg_super", s: "light", f: "gauss", t: 3, b: "Cyborg Heavy Body" },
	{ d: "Lancer Python Hover", c: 300, w: 8350, k: "tank_heavy", s: "light", f: "rocket", t: 3, b: "Python" },
	{ d: "Hyper Velocity Cannon Mantis Hover", c: 305, w: 9300, k: "tank_heavy", s: "light", f: "cannon", t: 3, b: "Mantis" },
	{ d: "Needle Gun Leopard Half-tracks", c: 314, w: 4750, k: "tank_light", s: "light", f: "gauss", t: 3, b: "Leopard" },
	{ d: "Tank Killer Mantis Hover", c: 330, w: 6600, k: "tank_heavy", s: "light", f: "rocket", t: 3, b: "Mantis" },
	{ d: "Tank Killer Panther Hover", c: 342, w: 7800, k: "tank_medium", s: "light", f: "rocket", t: 3, b: "Panther" },
	{ d: "Pulse Laser Panther Hover", c: 342, w: 8000, k: "tank_medium", s: "light", f: "energy", t: 3, b: "Panther" },
	{ d: "Needle Gun Leopard Hover", c: 342, w: 3250, k: "tank_light", s: "light", f: "gauss", t: 3, b: "Leopard" },
	{ d: "Mini-Rocket Array Cobra Tracks", c: 203, w: 15250, k: "tank_medium", s: "medium", f: "rocket", t: 3, b: "Cobra", i: 1 },
	{ d: "Medium Cannon Viper Tracks", c: 217, w: 9500, k: "tank_light", s: "medium", f: "cannon", t: 3, b: "Viper" },
	{ d: "Medium Cannon Scorpion Half-tracks", c: 218, w: 12500, k: "tank_medium", s: "medium", f: "cannon", t: 3, b: "Scorpion" },
	{ d: "Assault Gun Panther Half-tracks", c: 224, w: 13100, k: "tank_medium", s: "medium", f: "mg", t: 3, b: "Panther" },
	{ d: "Inferno Cobra Hover", c: 225, w: 11000, k: "tank_medium", s: "medium", f: "flame", t: 3, b: "Cobra" },
	{ d: "Lancer Cobra Half-tracks", c: 230, w: 10250, k: "tank_medium", s: "medium", f: "rocket", t: 3, b: "Cobra" },
	{ d: "Medium Cannon Cobra Half-tracks", c: 230, w: 15000, k: "tank_medium", s: "medium", f: "cannon", t: 3, b: "Cobra" },
	{ d: "Assault Gun Python Half-tracks", c: 230, w: 14100, k: "tank_heavy", s: "medium", f: "mg", t: 3, b: "Python" },
	{ d: "Lancer Scorpion Tracks", c: 237, w: 11500, k: "tank_medium", s: "medium", f: "rocket", t: 3, b: "Scorpion" },
	{ d: "Bunker Buster Scorpion Tracks", c: 237, w: 11500, k: "tank_medium", s: "medium", f: "rocket", t: 3, b: "Scorpion" },
	{ d: "Medium Cannon Scorpion Hover", c: 247, w: 9500, k: "tank_medium", s: "medium", f: "cannon", t: 3, b: "Scorpion" },
	{ d: "Bunker Buster Panther Half-tracks", c: 249, w: 12750, k: "tank_medium", s: "medium", f: "rocket", t: 3, b: "Panther" },
	{ d: "Bunker Buster Cobra Tracks", c: 253, w: 15250, k: "tank_medium", s: "medium", f: "rocket", t: 3, b: "Cobra" },
	{ d: "Lancer Cobra Tracks", c: 253, w: 15250, k: "tank_medium", s: "medium", f: "rocket", t: 3, b: "Cobra" },
	{ d: "Inferno Python Hover", c: 260, w: 13100, k: "tank_heavy", s: "medium", f: "flame", t: 3, b: "Python" },
	{ d: "Medium Cannon Cobra Hover", c: 265, w: 11000, k: "tank_medium", s: "medium", f: "cannon", t: 3, b: "Cobra" },
	{ d: "Lancer Mantis Tracks", c: 267, w: 16000, k: "tank_heavy", s: "medium", f: "rocket", t: 3, b: "Mantis" },
	{ d: "Bunker Buster Mantis Tracks", c: 267, w: 16000, k: "tank_heavy", s: "medium", f: "rocket", t: 3, b: "Mantis" },
	{ d: "Bombard Scorpion Half-tracks", c: 268, w: 12500, k: "tank_medium", s: "medium", f: "mortar", t: 3, b: "Scorpion", i: 1 },
	{ d: "Bombard Cobra Half-tracks", c: 280, w: 15000, k: "tank_medium", s: "medium", f: "mortar", t: 3, b: "Cobra", i: 1 },
	{ d: "Pepperpot Retribution Half-tracks", c: 287, w: 9500, k: "tank_medium", s: "medium", f: "mortar", t: 3, b: "Retribution", i: 1 },
	{ d: "Flashlight Retribution Tracks", c: 294, w: 11550, k: "tank_medium", s: "medium", f: "energy", t: 3, b: "Retribution" },
	{ d: "Bombard Scorpion Hover", c: 297, w: 9500, k: "tank_medium", s: "medium", f: "mortar", t: 3, b: "Scorpion", i: 1 },
	{ d: "Medium Cannon Python Hover", c: 300, w: 13100, k: "tank_heavy", s: "medium", f: "cannon", t: 3, b: "Python" },
	{ d: "Tank Killer Cobra Tracks", c: 303, w: 15300, k: "tank_medium", s: "medium", f: "rocket", t: 3, b: "Cobra" },
	{ d: "Hyper Velocity Cannon Panther Hover", c: 317, w: 10500, k: "tank_medium", s: "medium", f: "cannon", t: 3, b: "Panther" },
	{ d: "Hyper Velocity Cannon Python Hover", c: 325, w: 11100, k: "tank_heavy", s: "medium", f: "cannon", t: 3, b: "Python" },
	{ d: "Assault Cannon Tiger Hover", c: 327, w: 12400, k: "tank_heavy", s: "medium", f: "cannon", t: 3, b: "Tiger" },
	{ d: "Pulse Laser Retribution Tracks", c: 344, w: 11750, k: "tank_medium", s: "medium", f: "energy", t: 3, b: "Retribution" },
	{ d: "Tank Killer Tiger Tracks", c: 359, w: 25050, k: "tank_heavy", s: "heavy", f: "rocket", t: 4, b: "Tiger" },
	{ d: "Pulse Laser Tiger Tracks", c: 359, w: 25250, k: "tank_heavy", s: "heavy", f: "energy", t: 4, b: "Tiger" },
	{ d: "Heavy Cannon Mantis Tracks", c: 367, w: 23750, k: "tank_heavy", s: "heavy", f: "cannon", t: 4, b: "Mantis" },
	{ d: "Heavy Cannon Python Tracks", c: 385, w: 28250, k: "tank_heavy", s: "heavy", f: "cannon", t: 4, b: "Python" },
	{ d: "Pulse Laser Wyvern Tracks", c: 393, w: 26750, k: "tank_heavy", s: "heavy", f: "energy", t: 4, b: "Wyvern" },
	{ d: "Ripple Rockets Panther Half-tracks", c: 399, w: 32500, k: "tank_medium", s: "heavy", f: "rocket", t: 4, b: "Panther", i: 1 },
	{ d: "Heavy Cannon Tiger Tracks", c: 409, w: 32750, k: "tank_heavy", s: "heavy", f: "cannon", t: 4, b: "Tiger" },
	{ d: "Needle Gun Tiger Tracks", c: 409, w: 25750, k: "tank_heavy", s: "heavy", f: "gauss", t: 4, b: "Tiger" },
	{ d: "Twin Assault Cannon Vengeance Tracks", c: 430, w: 23750, k: "tank_heavy", s: "heavy", f: "cannon", t: 4, b: "Vengeance" },
	{ d: "Howitzer Tiger Tracks", c: 434, w: 34750, k: "tank_heavy", s: "heavy", f: "howitzer", t: 4, b: "Tiger", i: 1 },
	{ d: "Scourge Missile Tiger Tracks", c: 459, w: 25150, k: "tank_heavy", s: "heavy", f: "missile", t: 4, b: "Tiger" },
	{ d: "Scourge Missile Wyvern Tracks", c: 493, w: 26650, k: "tank_heavy", s: "heavy", f: "missile", t: 4, b: "Wyvern" },
	{ d: "Gauss Cannon Python Tracks", c: 535, w: 25250, k: "tank_heavy", s: "heavy", f: "gauss", t: 4, b: "Python" },
	{ d: "Gauss Cannon Tiger Tracks", c: 559, w: 29750, k: "tank_heavy", s: "heavy", f: "gauss", t: 4, b: "Tiger" },
	{ d: "Heavy Laser Tiger Tracks", c: 559, w: 29750, k: "tank_heavy", s: "heavy", f: "energy", t: 4, b: "Tiger" },
	{ d: "Gauss Cannon Vengeance Tracks", c: 580, w: 23750, k: "tank_heavy", s: "heavy", f: "gauss", t: 4, b: "Vengeance" },
	{ d: "Heavy Laser Vengeance Tracks", c: 580, w: 23750, k: "tank_heavy", s: "heavy", f: "energy", t: 4, b: "Vengeance" },
	{ d: "Gauss Cannon Wyvern Tracks", c: 593, w: 31250, k: "tank_heavy", s: "heavy", f: "gauss", t: 4, b: "Wyvern" },
	{ d: "Heavy Laser Wyvern Tracks", c: 593, w: 31250, k: "tank_heavy", s: "heavy", f: "energy", t: 4, b: "Wyvern" },
	{ d: "Plasma Cannon Wyvern Tracks", c: 593, w: 56250, k: "tank_heavy", s: "heavy", f: "cannon", t: 4, b: "Wyvern" },
	{ d: "Needle Gun Retaliation Tracks", c: 351, w: 4375, k: "tank_light", s: "light", f: "gauss", t: 4, b: "Retaliation" },
	{ d: "Hyper Velocity Cannon Tiger Hover", c: 352, w: 12900, k: "tank_heavy", s: "light", f: "cannon", t: 4, b: "Tiger" },
	{ d: "Pulse Laser Retribution Hover", c: 360, w: 5000, k: "tank_medium", s: "light", f: "energy", t: 4, b: "Retribution" },
	{ d: "Tank Killer Tiger Hover", c: 377, w: 10200, k: "tank_heavy", s: "light", f: "rocket", t: 4, b: "Tiger" },
	{ d: "Pulse Laser Tiger Hover", c: 377, w: 10400, k: "tank_heavy", s: "light", f: "energy", t: 4, b: "Tiger" },
	{ d: "Needle Gun Retribution Tracks", c: 394, w: 12250, k: "tank_medium", s: "light", f: "gauss", t: 4, b: "Retribution" },
	{ d: "Pulse Laser Vengeance Hover", c: 400, w: 8000, k: "tank_heavy", s: "light", f: "energy", t: 4, b: "Vengeance" },
	{ d: "Scourge Missile Mantis Hover", c: 430, w: 6700, k: "tank_heavy", s: "light", f: "missile", t: 4, b: "Mantis" },
	{ d: "Scourge Missile Retribution Tracks", c: 444, w: 11650, k: "tank_medium", s: "light", f: "missile", t: 4, b: "Retribution" },
	{ d: "Vindicator SAM Retribution Hover", c: 460, w: 5300, k: "tank_medium", s: "light", f: "missile", t: 4, b: "Retribution" },
	{ d: "Scourge Missile Retribution Hover", c: 460, w: 4900, k: "tank_medium", s: "light", f: "missile", t: 4, b: "Retribution" },
	{ d: "Rail Gun Retribution Hover", c: 460, w: 6500, k: "tank_medium", s: "light", f: "gauss", t: 4, b: "Retribution" },
	{ d: "Scourge Missile Tiger Hover", c: 477, w: 10300, k: "tank_heavy", s: "light", f: "missile", t: 4, b: "Tiger" },
	{ d: "Rail Gun Tiger Hover", c: 477, w: 11900, k: "tank_heavy", s: "light", f: "gauss", t: 4, b: "Tiger" },
	{ d: "Vindicator SAM Vengeance Hover", c: 500, w: 8300, k: "tank_heavy", s: "light", f: "missile", t: 4, b: "Vengeance" },
	{ d: "Scourge Missile Vengeance Hover", c: 500, w: 7900, k: "tank_heavy", s: "light", f: "missile", t: 4, b: "Vengeance" },
	{ d: "Seraph Missile Array Retaliation Hover", c: 512, w: 2350, k: "tank_light", s: "light", f: "missile", t: 4, b: "Retaliation", i: 1 },
	{ d: "Heavy Cannon Cobra Tracks", c: 353, w: 23000, k: "tank_medium", s: "medium", f: "cannon", t: 4, b: "Cobra" },
	{ d: "Heavy Cannon Cobra Hover", c: 365, w: 14000, k: "tank_medium", s: "medium", f: "cannon", t: 4, b: "Cobra" },
	{ d: "Heavy Cannon Mantis Hover", c: 380, w: 14300, k: "tank_heavy", s: "medium", f: "cannon", t: 4, b: "Mantis" },
	{ d: "Tank Killer Vengeance Tracks", c: 380, w: 19050, k: "tank_heavy", s: "medium", f: "rocket", t: 4, b: "Vengeance" },
	{ d: "Pulse Laser Vengeance Tracks", c: 380, w: 19250, k: "tank_heavy", s: "medium", f: "energy", t: 4, b: "Vengeance" },
	{ d: "Heavy Cannon Python Hover", c: 400, w: 16100, k: "tank_heavy", s: "medium", f: "cannon", t: 4, b: "Python" },
	{ d: "Rail Gun Mantis Tracks", c: 417, w: 17750, k: "tank_heavy", s: "medium", f: "gauss", t: 4, b: "Mantis" },
	{ d: "Scourge Missile Mantis Tracks", c: 417, w: 16150, k: "tank_heavy", s: "medium", f: "missile", t: 4, b: "Mantis" },
	{ d: "Heavy Cannon Tiger Hover", c: 427, w: 17900, k: "tank_heavy", s: "medium", f: "cannon", t: 4, b: "Tiger" },
	{ d: "Rail Gun Panther Tracks", c: 428, w: 20750, k: "tank_medium", s: "medium", f: "gauss", t: 4, b: "Panther" },
	{ d: "Needle Gun Vengeance Tracks", c: 430, w: 19750, k: "tank_heavy", s: "medium", f: "gauss", t: 4, b: "Vengeance" },
	{ d: "Scourge Missile Python Tracks", c: 435, w: 20650, k: "tank_heavy", s: "medium", f: "missile", t: 4, b: "Python" },
	{ d: "Rail Gun Retribution Tracks", c: 444, w: 13250, k: "tank_medium", s: "medium", f: "gauss", t: 4, b: "Retribution" },
	{ d: "Rail Gun Vengeance Tracks", c: 480, w: 20750, k: "tank_heavy", s: "medium", f: "gauss", t: 4, b: "Vengeance" },
	{ d: "Scourge Missile Vengeance Tracks", c: 480, w: 19150, k: "tank_heavy", s: "medium", f: "missile", t: 4, b: "Vengeance" },
	{ d: "Gauss Cannon Tiger Hover", c: 577, w: 14900, k: "tank_heavy", s: "medium", f: "gauss", t: 4, b: "Tiger" },
	{ d: "Ground Shaker Tiger Tracks", c: 759, w: 44750, k: "tank_heavy", s: "heavy", f: "howitzer", t: 5, b: "Tiger", i: 1 },
	{ d: "Seraph Missile Array Vengeance Hover", c: 600, w: 8500, k: "tank_heavy", s: "light", f: "missile", t: 5, b: "Vengeance", i: 1 },
	{ d: "Gauss Cannon Vengeance Hover", c: 600, w: 12500, k: "tank_heavy", s: "medium", f: "gauss", t: 5, b: "Vengeance" },
	{ d: "Hellstorm Tiger Tracks", c: 609, w: 34750, k: "tank_heavy", s: "medium", f: "howitzer", t: 5, b: "Tiger", i: 1 },
	{ d: "Seraph Missile Array Gauss Cannon Dragon Hover", c: 1025, w: 19500, k: "tank_heavy", s: "medium", f: "missile", t: 5, b: "Dragon", i: 1 },
];
